Core/urls.py
from django.urls import include, path
from rest_framework import routers
from .views import *

router = routers.DefaultRouter()
router.register(r'produtos', ProdutoViewSet)
router.register(r'produtos_comprados', ProdutoLoteCompraViewSet)
router.register(r'lotes_de_compra', LoteCompraViewSet)

urlpatterns = [
    path('/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

Estoque/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('/', PaginaPrincipal.as_view(), name='estoque-principal'),

    path('/compra', PaginaDeCompra.as_view(), name='estoque-compra'),
    path('/compra/formulario', PaginaDeCargaPorFormulario.as_view(), name='estoque-compra-formulario'),
    path('/compra/arquivo', PaginaDeCargaPorArquivo.as_view(), name='estoque-compra-arquivo'),
    path('/compra/arquivo/modelo', download_do_arquivo_modelo, name='estoque-compra-arquivo_modelo'),

    path('/cadastro/produtos', PaginaCadastroProduto.as_view(), name='estoque-cadastro-produto'),

    path('/cadastro/lotes_compras', PaginaListaLotesDeCompra.as_view(), name='estoque-cadastro-lote_de_compra'),
    path('/lote_compra/listar', AJAXListaLotesDeCompra.as_view(), name='lote_de_compra-listar'),
]

desafio_querotrabalharnawpensar/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.http import HttpResponse
from django.shortcuts import redirect

urlpatterns = [
    # admin
    path('admin', admin.site.urls),

    path('api', include('Core.urls')),
    # raiz
    path('', lambda request: redirect('estoque-principal')),

    # credenciais
    path('login', include('Autenticacao.urls'), name='login'),

    # modulos
    path('estoque', include('Estoque.urls')),

    # default
    re_path(r'^.', lambda request: HttpResponse('<h1>404</h1>')),
]

Core/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel


class ProdutoCategoria(TimeStampedModel, models.Model):
    nome = models.TextField(max_length=50)

    class Meta:
        db_table = 'PRODUTO_CATEGORIA'
        verbose_name_plural = "Categorias de Produto"

    def __str__(self):
        return self.nome


class Produto(TimeStampedModel, models.Model):
    nome = models.TextField(max_length=50, unique=True)
    preco = models.FloatField(default=0)
    categoria = models.ForeignKey(ProdutoCategoria, null=True, on_delete=models.PROTECT)
    quantidade = models.PositiveIntegerField(default=0)

    class Meta:
        db_table = 'PRODUTO'

    def __str__(self):
        return self.nome


class LoteCompraStatus(TimeStampedModel, models.Model):
    nome = models.TextField(max_length=50)

    class Meta:
        db_table = 'LOTE_COMPRA_STATUS'
        verbose_name_plural = "Status de Lotes de Compra"

    def __str__(self):
        return self.nome


class LoteCompra(TimeStampedModel, models.Model):
    abertura = models.DateTimeField(auto_now_add=True)
    fechamento = models.DateTimeField(blank=True)
    status = models.ForeignKey(LoteCompraStatus, null=True, on_delete=models.PROTECT)

    @property
    def custo(self):
        return sum([produto_lote_compra.preco * produto_lote_compra.quantidade for produto_lote_compra in self.produtos_comprados.all()])

    class Meta:
        db_table = 'LOTE_COMPRA'
        verbose_name_plural = "Lotes de Compra"

    def __str__(self):
        return f'{self.id} - {self.fechamento.day}/{self.fechamento.month}/{self.fechamento.year}'


class ProdutoLoteCompra(TimeStampedModel, models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.PROTECT)
    lote = models.ForeignKey(LoteCompra, related_name='produtos_comprados', on_delete=models.PROTECT)
    preco_anterior = models.FloatField(default=0)
    quantidade = models.IntegerField()
    preco = models.FloatField()
    preco_novo = models.FloatField()

    @property
    def custo(self):
        return self.quantidade * self.preco

    def calcular_preco(self):
        estoque_anterior = self.produto.quantidade
        custo_da_compra = self.preco * self.quantidade
        saldo_custo_anterior = estoque_anterior * self.preco_anterior
        novo_estoque = estoque_anterior + self.quantidade
        return (custo_da_compra + saldo_custo_anterior) / novo_estoque

    '''def estoque(self):
        preco_da_compra = self.preco * self.quantidade
        return abs((self.preco_novo - preco_da_compra) / self.preco_anterior)'''

    class Meta:
        db_table = 'PRODUTO_LOTE_COMPRA'
        verbose_name_plural = "Produtos de Lote de Compra"

    def __str__(self):
        return f'Lote: {self.lote_id} - Nome: {self.produto.nome}'

Estoque/forms.py
from django import forms
from django.core.exceptions import ValidationError
from Core.models import Produto


class ProdutoLoteForm(forms.Form):
    nome = forms.CharField(label='Nome do Produto', required=False)
    quantidade = forms.CharField(label='Quantidade', required=False)
    preco = forms.CharField(label='Preço Unitario', required=False)

    def is_valid(self):
        return True


class ArquivoForm(forms.Form):
    arquivo_de_carga = forms.FileField()

    def clean_arquivo_de_carga(self):
        arquivo_de_carga = self.cleaned_data.get("arquivo_de_carga")

        if not str(arquivo_de_carga).endswith('.csv'):
            raise ValidationError('Formato inválido!')

        return self.cleaned_data

Estoque/views.py
from django.views.generic import *
from .forms import *
from .services import *
from django.views.generic.edit import CreateView
from django.forms import formset_factory
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.shortcuts import redirect


class PaginaPrincipal(TemplateView):
    template_name = 'estoque/base.html'


class PaginaDeCompra(TemplateView):
    template_name = 'estoque/compra/base.html'


class PaginaDeCargaPorFormulario(SuccessMessageMixin, FormView):
    template_name = 'estoque/compra/carga_formulario.html'
    form_class = formset_factory(ProdutoLoteForm, extra=0, min_num=1, validate_min=True)
    success_url = '../compra'
    success_message = "Carga realizada!"

    def form_valid(self, form):
        form_set = form
        servico_de_carga = ServicoCargaCompra()

        if not servico_de_carga.processar_formulario(form_set):
            print([form.errors for form in form_set.forms])
            return self.form_invalid(form_set)

        messages.success(request=self.request, message=self.success_message)
        return redirect(self.success_url)


class PaginaDeCargaPorArquivo(SuccessMessageMixin, FormView):
    template_name = 'estoque/compra/carga_arquivo.html'
    form_class = ArquivoForm
    success_url = '/estoque/compra'
    success_message = "Carga realizada!"

    def post(self, request):
        form_arquivo = ArquivoForm(request.POST, request.FILES)
        caminho_arquivo = request.FILES['arquivo_de_carga'].temporary_file_path()
        servico_de_carga = ServicoCargaCompra()

        if not form_arquivo.is_valid():
            return self.form_invalid(form_arquivo)

        if not servico_de_carga.processar_arquivo_csv(caminho_arquivo):
            [form_arquivo.add_error('arquivo_de_carga', forms.ValidationError(mensagem)) for mensagem in servico_de_carga.erros]
            print(form_arquivo.errors)
            return self.form_invalid(form_arquivo)

        return self.form_valid(form_arquivo)


def download_do_arquivo_modelo(request):
    return ServicoCargaCompra.gerar_modelo_de_arquivo()


class PaginaCadastroProduto(SuccessMessageMixin, CreateView):
    template_name = "estoque/cadastro/produto.html"
    model = Produto
    fields = ['nome']
    success_url = '../../'
    success_message = "Produto cadastrado!"


class PaginaListaLotesDeCompra(TemplateView):
    template_name = 'estoque/cadastro/lote_de_compra.html'


class AJAXListaLotesDeCompra(BaseDatatableView):
    model = LoteCompra

templates/estoque/compra/base.html
{% extends 'estoque/base.html' %}

{% block cabecalho_titulo %}
    Compras
{% endblock %}

{% block cabecalho_descricao %}
    Comprar produtos através do formulário de compra.
    <br>
    Importar um arquivo de compra em lote.
{% endblock %}

templates/estoque/compra/carga_arquivo.html
{% extends 'estoque/compra/base.html' %}

{% block cabecalho_descricao %}

    Carga de lote de compra por arquivo .csv
    <br>
    Para fazer o download do modelo de arquivo <a href="{% url 'estoque-compra-arquivo_modelo' %}">Clique Aqui</a>.

{% endblock %}

{% block main_estoque%}
    <div class="card mb-4">

        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Importação de Arquivo
        </div>

        <div class="card-body">
            {% if perms.Core.add_lotecompra %}

                <form method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

                            {{ form }}

                        <input type="submit" class="btn btn-success btn-sm" value="Enviar">
                    </div>
                </form>

            {% else %}

                <p>Você não tem permissão para comprar produtos.</p>

            {% endif %}

        </div>
    </div>

{% endblock %}

templates/estoque/compra/carga_formulario.html
{% extends 'estoque/compra/base.html' %}

{% block cabecalho_descricao %}
    Formulário de compra de produtos.
{% endblock %}

{% block main_estoque%}
    <div class="card mb-4">

        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Formulário de compra
        </div>

        <div class="card-body">

            {% if perms.Core.add_lotecompra %}

                <form method="post">
                    {{ form.management_form }}
                    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

                    <div class="form-row">
                        <div class="form-group">
                            <ul id="form_set">
                                {% for form_ in form %}
                                    <li class='no_error'>
                                        {{ form_ }}
                                        <input type="button" class="btn btn-danger btn-sm" value="Remover" onClick="remover_produto(event)">
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <input type="button" class="btn btn-primary btn-sm" value="Adicionar" onClick="adicionar_produto(event)">
                            <input type="submit" class="btn btn-success btn-sm" value="Carregar">
                        </div>
                    </div>
                </form>

                <script defer>
                    function adicionar_produto()
                    {
                        // Obtem o indicie atual do formset e incrementa ...
                        let novo_index_form_set = parseInt(document.querySelector('#id_form-TOTAL_FORMS').value) + 1

                        // Atribui novo indicie ao formset
                        document.querySelector('#id_form-TOTAL_FORMS').value = novo_index_form_set

                        // Gera um novo nó de produto ...
                        let novo_produto_node = document.querySelector('#form_set').lastElementChild.cloneNode(true)

                        // Atribui novo indicie a esse novo nó gerado ...
                        novo_produto_node.innerHTML = novo_produto_node.innerHTML.replace(/-\d-/g, `-${novo_index_form_set}-`)

                        // Limpa os nos filhos que são inputs, menos o botão ...
                        Array.from(novo_produto_node.children).filter(node => node.tagName == 'INPUT' && node.type != 'button').forEach(input => input.value = '')

                        // Adiciona o novo no na lista de produtos ...
                        document.querySelector('#form_set').append(novo_produto_node)
                    }
                    function remover_produto(event)
                    {
                        // Obtem o indicie atual do formset e decrementa ...
                        let novo_index_form_set = parseInt(document.querySelector('#id_form-TOTAL_FORMS').value) - 1

                        // Atribui novo indicie ao formset ...
                        document.querySelector('#id_form-TOTAL_FORMS').value = novo_index_form_set

                        // Remove o nó alvo ...
                        event.target.parentNode.remove()

                        // Reatribui indicies dos produtos ...
                        Array.from(document.querySelector('#form_set').children).forEach((li, index) => {
                            Array.from(li.children).forEach(input => {
                                input.innerHTML = input.innerHTML.replace(/-\d-/g, `-${index}-`)
                            })
                        })
                    }
                </script>

            {% else %}

                <p>Você não tem permissão para comprar produtos.</p>

            {% endif %}
        </div>
    </div>
{% endblock %}