Core/urls.py
from django.urls import include, path
from rest_framework import routers
from .views import *

router = routers.DefaultRouter()
router.register(r'produtos', ProdutoViewSet)
router.register(r'produtos_comprados', ProdutoLoteCompraViewSet)
router.register(r'lotes_de_compra', LoteCompraViewSet)

urlpatterns = [
    path('/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

Estoque/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('/', PaginaPrincipal.as_view(), name='estoque-principal'),

    path('/compra', PaginaDeCompra.as_view(), name='estoque-compra'),
    path('/compra/formulario', PaginaDeCargaPorFormulario.as_view(), name='estoque-compra-formulario'),
    path('/compra/arquivo', PaginaDeCargaPorArquivo.as_view(), name='estoque-compra-arquivo'),
    path('/compra/arquivo/modelo', download_do_arquivo_modelo, name='estoque-compra-arquivo_modelo'),

    path('/cadastro/produtos', PaginaCadastroProduto.as_view(), name='estoque-cadastro-produto'),

    path('/cadastro/lotes_compras', PaginaListaLotesDeCompra.as_view(), name='estoque-cadastro-lote_de_compra'),
    path('/lote_compra/listar', AJAXListaLotesDeCompra.as_view(), name='lote_de_compra-listar'),
]

desafio_querotrabalharnawpensar/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.http import HttpResponse
from django.shortcuts import redirect

urlpatterns = [
    # admin
    path('admin', admin.site.urls),

    path('api', include('Core.urls')),
    # raiz
    path('', lambda request: redirect('estoque-principal')),

    # credenciais
    path('login', include('Autenticacao.urls'), name='login'),

    # modulos
    path('estoque', include('Estoque.urls')),

    # default
    re_path(r'^.', lambda request: HttpResponse('<h1>404</h1>')),
]

Core/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel


class ProdutoCategoria(TimeStampedModel, models.Model):
    nome = models.TextField(max_length=50)

    class Meta:
        db_table = 'PRODUTO_CATEGORIA'
        verbose_name_plural = "Categorias de Produto"

    def __str__(self):
        return self.nome


class Produto(TimeStampedModel, models.Model):
    nome = models.TextField(max_length=50, unique=True)
    preco = models.FloatField(default=0)
    categoria = models.ForeignKey(ProdutoCategoria, null=True, on_delete=models.PROTECT)
    quantidade = models.PositiveIntegerField(default=0)

    class Meta:
        db_table = 'PRODUTO'

    def __str__(self):
        return self.nome


class LoteCompraStatus(TimeStampedModel, models.Model):
    nome = models.TextField(max_length=50)

    class Meta:
        db_table = 'LOTE_COMPRA_STATUS'
        verbose_name_plural = "Status de Lotes de Compra"

    def __str__(self):
        return self.nome


class LoteCompra(TimeStampedModel, models.Model):
    abertura = models.DateTimeField(auto_now_add=True)
    fechamento = models.DateTimeField(blank=True)
    status = models.ForeignKey(LoteCompraStatus, null=True, on_delete=models.PROTECT)

    @property
    def custo(self):
        return sum([produto_lote_compra.preco * produto_lote_compra.quantidade for produto_lote_compra in self.produtos_comprados.all()])

    class Meta:
        db_table = 'LOTE_COMPRA'
        verbose_name_plural = "Lotes de Compra"

    def __str__(self):
        return f'{self.id} - {self.fechamento.day}/{self.fechamento.month}/{self.fechamento.year}'


class ProdutoLoteCompra(TimeStampedModel, models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.PROTECT)
    lote = models.ForeignKey(LoteCompra, related_name='produtos_comprados', on_delete=models.PROTECT)
    preco_anterior = models.FloatField(default=0)
    quantidade = models.IntegerField()
    preco = models.FloatField()
    preco_novo = models.FloatField()

    @property
    def custo(self):
        return self.quantidade * self.preco

    def calcular_preco(self):
        estoque_anterior = self.produto.quantidade
        custo_da_compra = self.preco * self.quantidade
        saldo_custo_anterior = estoque_anterior * self.preco_anterior
        novo_estoque = estoque_anterior + self.quantidade
        return (custo_da_compra + saldo_custo_anterior) / novo_estoque

    '''def estoque(self):
        preco_da_compra = self.preco * self.quantidade
        return abs((self.preco_novo - preco_da_compra) / self.preco_anterior)'''

    class Meta:
        db_table = 'PRODUTO_LOTE_COMPRA'
        verbose_name_plural = "Produtos de Lote de Compra"

    def __str__(self):
        return f'Lote: {self.lote_id} - Nome: {self.produto.nome}'

Estoque/forms.py
from django import forms
from django.core.exceptions import ValidationError
from Core.models import Produto


class ProdutoLoteForm(forms.Form):
    nome = forms.CharField(label='Nome do Produto', required=False)
    quantidade = forms.CharField(label='Quantidade', required=False)
    preco = forms.CharField(label='Preço Unitario', required=False)

    def is_valid(self):
        return True


class ArquivoForm(forms.Form):
    arquivo_de_carga = forms.FileField()

    def clean_arquivo_de_carga(self):
        arquivo_de_carga = self.cleaned_data.get("arquivo_de_carga")

        if not str(arquivo_de_carga).endswith('.csv'):
            raise ValidationError('Formato inválido!')

        return self.cleaned_data

Estoque/views.py
from django.views.generic import *
from .forms import *
from .services import *
from django.views.generic.edit import CreateView
from django.forms import formset_factory
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.shortcuts import redirect


class PaginaPrincipal(TemplateView):
    template_name = 'estoque/base.html'


class PaginaDeCompra(TemplateView):
    template_name = 'estoque/compra/base.html'


class PaginaDeCargaPorFormulario(SuccessMessageMixin, FormView):
    template_name = 'estoque/compra/carga_formulario.html'
    form_class = formset_factory(ProdutoLoteForm, extra=0, min_num=1, validate_min=True)
    success_url = '../compra'
    success_message = "Carga realizada!"

    def form_valid(self, form):
        form_set = form
        servico_de_carga = ServicoCargaCompra()

        if not servico_de_carga.processar_formulario(form_set):
            print([form.errors for form in form_set.forms])
            return self.form_invalid(form_set)

        messages.success(request=self.request, message=self.success_message)
        return redirect(self.success_url)


class PaginaDeCargaPorArquivo(SuccessMessageMixin, FormView):
    template_name = 'estoque/compra/carga_arquivo.html'
    form_class = ArquivoForm
    success_url = '/estoque/compra'
    success_message = "Carga realizada!"

    def post(self, request):
        form_arquivo = ArquivoForm(request.POST, request.FILES)
        caminho_arquivo = request.FILES['arquivo_de_carga'].temporary_file_path()
        servico_de_carga = ServicoCargaCompra()

        if not form_arquivo.is_valid():
            return self.form_invalid(form_arquivo)

        if not servico_de_carga.processar_arquivo_csv(caminho_arquivo):
            [form_arquivo.add_error('arquivo_de_carga', forms.ValidationError(mensagem)) for mensagem in servico_de_carga.erros]
            print(form_arquivo.errors)
            return self.form_invalid(form_arquivo)

        return self.form_valid(form_arquivo)


def download_do_arquivo_modelo(request):
    return ServicoCargaCompra.gerar_modelo_de_arquivo()


class PaginaCadastroProduto(SuccessMessageMixin, CreateView):
    template_name = "estoque/cadastro/produto.html"
    model = Produto
    fields = ['nome']
    success_url = '../../'
    success_message = "Produto cadastrado!"


class PaginaListaLotesDeCompra(TemplateView):
    template_name = 'estoque/cadastro/lote_de_compra.html'


class AJAXListaLotesDeCompra(BaseDatatableView):
    model = LoteCompra

templates/estoque/cadastro/base.html
{% extends 'estoque/base.html' %}

{% block cabecalho_titulo %}
    Cadastro
{% endblock %}

{% block cabecalho_descricao %}
    Cadastrar um produto
    <br>
    Visualizar os lotes de compras
{% endblock %}

templates/estoque/cadastro/lote_de_compra.html
{% extends 'estoque/cadastro/base.html' %}

{% block cabecalho_descricao %}
    Lotes de Compra
{% endblock %}

{% block main_estoque %}

    {% if perms.Core.view_lotecompra %}

        <div id="produtos_comprados_modal" class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content" style="width: fit-content;">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Lista de Produtos</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <table id="produtos_comprados" class="table table-bordered table-hover" data-server-side="true" data-ajax="/api/produtos_comprados/?format=datatables">
                            <thead>
                            <tr>
                                <th data-data="id">ID</th>
                                <th data-data="produto.nome">Nome</th>
                                <th data-data="preco">Preço Unitário</th>
                                <th data-data="quantidade">Quantidade Adiquirida</th>
                                <th data-data="custo">Custo</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="lotes_de_compra" class="table table-bordered table-hover" style="width: 70%" data-server-side="true" data-ajax="/api/lotes_de_compra/?format=datatables">
                        <thead>
                        <tr>
                            <th data-data="id">ID</th>
                            <th data-data="abertura">Abertura</th>
                            <th data-data="fechamento">Fechamento</th>
                            <th data-data="custo">Custo</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>

        <script src="//code.jquery.com/jquery-1.12.4.js"></script>
        <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        <script src="//cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>

        <script defer>
            let tabela_de_produtos_comprados = $('#produtos_comprados').DataTable({
                destroy: true,
                dom: 'lfrtip',
                language: {
                    lengthMenu: "Mostrando _MENU_ registros por página",
                    zeroRecords: "Nenhum registro encontrado",
                    info: "Mostrando página _PAGE_ de _PAGES_",
                    infoEmpty: "Registros indisponíveis",
                    paginate: {
                        previous: "Anterior",
                        next: "Próxima",
                    },
                    infoFiltered: "",
                    search: "Procurar"
                }
            })
            let tabela_de_lotes = $('#lotes_de_compra').DataTable({
                dom: 'lfrtip',
                language: {
                    lengthMenu: "Mostrando _MENU_ registros por página",
                    zeroRecords: "Nenhum registro encontrado",
                    info: "Mostrando página _PAGE_ de _PAGES_",
                    infoEmpty: "Registros indisponíveis",
                    paginate: {
                        previous: "Anterior",
                        next: "Próxima",
                    },
                    infoFiltered: "",
                    search: "Procurar"
                },
                drawCallback: function( settings ) {
                    $('tbody > tr').on('click', event => {
                        let id = event.target.parentElement.firstElementChild.innerText
                        tabela_de_produtos_comprados.ajax.url( `/api/produtos_comprados/?search=${id}&search_fields=lote__id&format=datatables` ).load();
                        $('#produtos_comprados_modal').modal('show')
                    })
                }
            })
           // $('#produtos_comprados_modal').on('hide.bs.modal', event => {
            //    $('#produtos_comprados').DataTable().clear().destroy()
            //})

        </script>

    {% else %}

        <p>Você não tem permissão para visualizar lotes de compras.</p>

    {% endif %}

{% endblock %}

<!-- TODO acordeon dos produtos no lote ... -->

templates/estoque/cadastro/produto.html
{% extends 'estoque/cadastro/base.html' %}

{% block cabecalho_descricao %}
    Produtos
{% endblock %}

{% block main_estoque %}

    {% if perms.Core.add_produto %}

        <div class="card mb-4">
            <div class="card-body">
                <form action="" method="post">
                    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

                    {{ form }}

                    <input type="submit" class="btn btn-success btn-sm" value="Cadastrar" />
                </form>
            </div>
        </div>

        <script defer>
            let input_feio = document.querySelector('textarea')
            input_feio.parentElement.innerHTML = input_feio.parentElement.innerHTML.replace('textarea', 'input')
        </script>

    {% else %}

        <p>Você não tem permissão para cadastrar um produto.</p>

    {% endif %}

    {% if perms.Core.view_produto %}

        <div class="card mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="produtos" class="table table-bordered table-hover" style="width: 70%" data-server-side="true" data-ajax="/api/produtos/?format=datatables">
                        <thead>
                            <tr>
                                <th data-data="id">ID</th>
                                <th data-data="nome">Nome</th>
                                <th data-data="preco">Preco</th>
                                <th data-data="quantidade">Quantidade</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>

        <script src="//code.jquery.com/jquery-1.12.4.js"></script>
        <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        <script src="//cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>

        <script defer>
            $('#produtos').DataTable({
                dom: 'lfrtip',

                language: {
                    lengthMenu: "Mostrando _MENU_ registros por página",
                    zeroRecords: "Nenhum registro encontrado",
                    info: "Mostrando página _PAGE_ de _PAGES_",
                    infoEmpty: "Registros indisponíveis",
                    infoFiltered: "",
                    search: "Procurar"
                }
            })
        </script>

    {% else %}

        <p>Você não tem permissão para visualizar produtos.</p>

    {% endif %}

{% endblock %}